[package]
name = "mbid"
version = "0.1.0"
edition = "2024"

[dependencies]
discid = "0.7.0"
env_logger = "0.11.9"
musicbrainz_rs = { version = "0.12.0", default-features = false, features = ["blocking", "rustls"] }
